<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'cal.pi_flexform.sheetGeneral' => 'General Settings',
		'cal.pi_flexform.defaultView' => 'Default view',
		'cal.pi_flexform.isStatic' => 'Static view',
		'cal.pi_flexform.viewMonth' => 'Month',
		'cal.pi_flexform.viewYear' => 'Year',
		'cal.pi_flexform.viewList' => 'List',
		'cal.pi_flexform.viewWeek' => 'Week',
		'cal.pi_flexform.viewDay' => 'Day',
		'cal.pi_flexform.viewSingle' => 'Single Event',
		'cal.pi_flexform.viewAdmin' => 'Admin',
		'cal.pi_flexform.viewSearchEvent' => 'Search Event',
		'cal.pi_flexform.calendarName' => 'Calendar name',
		'cal.pi_flexform.defaultCalendarUid' => 'Default calendar',
		'cal.pi_flexform.allowSubscribe' =>'Allow to subscribe',
		'cal.pi_flexform.subscribeFeUser' => 'Allow FE user to subscribe',
		'cal.pi_flexform.subscribeWithCaptcha' => 'Force captcha to subscribe',
		
		'cal.pi_flexform.sheetYearView' => 'Year View',
		'cal.pi_flexform.yearViewPid' => 'Year view page',
		'cal.pi_flexform.yearTemplate' => 'Year template',
		
		'cal.pi_flexform.sheetMonthView' => 'Month View',
		'cal.pi_flexform.monthViewPid' => 'Month view page',
		'cal.pi_flexform.monthTemplate' => 'Month template',
		'cal.pi_flexform.monthSmallTemplate' => 'Month small template',
		'cal.pi_flexform.monthMediumTemplate' => 'Month medium template',
		'cal.pi_flexform.monthLargeTemplate' => 'Month large template',
		'cal.pi_flexform.thisMonthsEvents' => 'Show events of this month',
		
		'cal.pi_flexform.sheetWeekView' => 'Week View',
		'cal.pi_flexform.weekViewPid' => 'Week view page',
		'cal.pi_flexform.weekTemplate' => 'Week template',
		'cal.pi_flexform.weekStartDay' => 'Week start day',
		
		'cal.pi_flexform.sheetDayView' => 'Day View',
		'cal.pi_flexform.dayViewPid' => 'Day view page',
		'cal.pi_flexform.dayTemplate' => 'Day template',
		'cal.pi_flexform.dayStart' => 'Day start time (hhmm)',
		'cal.pi_flexform.dayEnd' => 'Day endtime (hhmm)',
		'cal.pi_flexform.gridLength' => 'Grid length',
		
		'cal.pi_flexform.sheetListView' => 'List View',
		'cal.pi_flexform.listViewPid' => 'List view page',
		'cal.pi_flexform.listTemplate' => 'List template',
		'cal.pi_flexform.starttime' => 'Start time',
		'cal.pi_flexform.endtime' => 'End time',
		'cal.pi_flexform.maxEvents' => 'Max events',
		
		'cal.pi_flexform.sheetEventView' => 'Event View',
		'cal.pi_flexform.eventViewPid' => 'Event view page',
		'cal.pi_flexform.eventTemplate' => 'Event template',
		'cal.pi_flexform.isPreview' => 'Show preview',
		'cal.pi_flexform.phpicalendarEventTemplate' => 'PhpICalendar event template',
		'cal.pi_flexform.createEventTemplate' => 'Create event template',
		'cal.pi_flexform.confirmEventTemplate' => 'Confirm event template',
		'cal.pi_flexform.deleteEventTemplate' => 'Delete event template',
		
		'cal.pi_flexform.sheetLocationView' => 'Location View',
		'cal.pi_flexform.locationViewPid' => 'Location view page',
		'cal.pi_flexform.locationTemplate' => 'Location template',
		'cal.pi_flexform.createLocationTemplate' => 'Create location template',
		'cal.pi_flexform.confirmLocationTemplate' => 'Confirm location template',
		
		'cal.pi_flexform.sheetOrganizerView' => 'Organizer View',
		'cal.pi_flexform.organizerViewPid' => 'Organizer view page',
		'cal.pi_flexform.organizerTemplate' => 'Organizer template',
		
		'cal.pi_flexform.sheetIcsView' => 'Ics View',
		'cal.pi_flexform.icsViewPid' => 'Ics view page',
		'cal.pi_flexform.icsTemplate' => 'Ics template',
		'cal.pi_flexform.calUid' => 'Calendar id',
		'cal.pi_flexform.showIcsLinks' => 'Show ics links',
		
		'cal.pi_flexform.sheetOtherView' => 'Other View',
		'cal.pi_flexform.sidebarTemplate' => 'Sidebar template',
		'cal.pi_flexform.searchBoxTemplate' => 'Searchbox template',
		'cal.pi_flexform.showLogin' => 'Show login',
		'cal.pi_flexform.showSearch' => 'Show search',
		'cal.pi_flexform.showJumps' => 'Show jumps',
		'cal.pi_flexform.showGoto' => 'Show goto',
		'cal.pi_flexform.showCategorySelection' => 'Show category selector',
		'cal.pi_flexform.showTomorrowEvents' => 'Show tomorrows events',
	),
	'de' => Array (
		'cal.pi_flexform.sheetGeneral' => 'Allgemeine Einstellungen',
		'cal.pi_flexform.defaultView' => 'Standardansicht',
		'cal.pi_flexform.viewMonth' => 'Monats-Ansicht',
		'cal.pi_flexform.viewYear' => 'Jahres-Ansicht',
		'cal.pi_flexform.viewList' => 'Listen-Ansicht',
		'cal.pi_flexform.viewWeek' => 'Wochen-Ansicht',
		'cal.pi_flexform.viewDay' => 'Tages-Ansicht',
		'cal.pi_flexform.viewSingle' => 'Einzel-Ansicht',
		'cal.pi_flexform.viewAdmin' => 'Admin',
		'cal.pi_flexform.calendarName' => 'Kalendername',
		'cal.pi_flexform.anonymousUserUid' => 'Anonymer Benutzer',
		'cal.pi_flexform.allowSubscribe' =>'Abonnieren erlauben',
		'cal.pi_flexform.subscribeFeUser' => 'FE-Benutzern abonnieren erlauben',
		'cal.pi_flexform.subscribeWithCaptcha' => 'Force captcha to subscribe',
		
		'cal.pi_flexform.sheetYearView' => 'Jahres-Ansicht',
		'cal.pi_flexform.yearViewPid' => 'Jahres-Ansicht Seite',
		'cal.pi_flexform.yearTemplate' => 'Jahres-Ansicht Template',
		
		'cal.pi_flexform.sheetMonthView' => 'Monats-Ansicht',
		'cal.pi_flexform.monthViewPid' => 'Monats-Ansicht Seite',
		'cal.pi_flexform.monthTemplate' => 'Monats-Ansicht Template',
		'cal.pi_flexform.monthSmallTemplate' => 'Monats Template small',
		'cal.pi_flexform.monthMediumTemplate' => 'Monats-Template medium',
		'cal.pi_flexform.monthLargeTemplate' => 'Monats-Template large',
		'cal.pi_flexform.thisMonthsEvents' => 'Zeige Ereignisse des Monats',
		
		'cal.pi_flexform.sheetWeekView' => 'Wochen-Ansicht',
		'cal.pi_flexform.weekViewPid' => 'Wochen-Ansicht Seite',
		'cal.pi_flexform.weekTemplate' => 'Wochen-Ansicht Template',
		'cal.pi_flexform.weekStartDay' => 'Wochenstarttag',
		
		'cal.pi_flexform.sheetDayView' => 'Tages-Ansicht',
		'cal.pi_flexform.dayViewPid' => 'Tages-Ansicht Seite',
		'cal.pi_flexform.dayTemplate' => 'Tages-Ansicht Template',
		'cal.pi_flexform.dayStart' => 'Tages Startzeit (hhmm)',
		'cal.pi_flexform.dayEnd' => 'Tages Endzeit (hhmm)',
		'cal.pi_flexform.gridLength' => 'Gitterlänge',
		
		'cal.pi_flexform.sheetListView' => 'Listen-Ansicht',
		'cal.pi_flexform.listViewPid' => 'Listen-Ansicht Seite',
		'cal.pi_flexform.listTemplate' => 'Listen-Ansicht Template',
		'cal.pi_flexform.starttime' => 'Startzeit (leer = jetzt)',
		'cal.pi_flexform.endtime' => 'Endzeit (leer = +1 Monat)',
		'cal.pi_flexform.maxEvents' => 'Höchstzahl der Ereignisse',
		
		'cal.pi_flexform.sheetEventView' => 'Ereignis-Ansicht',
		'cal.pi_flexform.eventViewPid' => 'Ereignis-Ansicht Seite',
		'cal.pi_flexform.eventTemplate' => 'Ereignis-Ansicht Template',
		'cal.pi_flexform.phpicalendarEventTemplate' => 'PhpICalendar Ereignis-Template',
		'cal.pi_flexform.createEventTemplate' => 'Ereignis erstellen Template',
		'cal.pi_flexform.confirmEventTemplate' => 'Ereignis bestätigen Template',
		'cal.pi_flexform.deleteEventTemplate' => 'Ereignis löschen Template',
		
		'cal.pi_flexform.sheetLocationView' => 'Ort-Ansicht',
		'cal.pi_flexform.locationViewPid' => 'Ort-Ansicht Seite',
		'cal.pi_flexform.locationTemplate' => 'Ort-Ansicht Template',
		'cal.pi_flexform.createLocationTemplate' => 'Ort erstellen Template',
		'cal.pi_flexform.confirmLocationTemplate' => 'Ort bestätigen Template',
		
		'cal.pi_flexform.sheetOrganizerView' => 'Organisator-Ansicht',
		'cal.pi_flexform.organizerViewPid' => 'Organisator-Ansicht Seite',
		'cal.pi_flexform.organizerTemplate' => 'Organisator-Ansicht Template',
		
		'cal.pi_flexform.sheetIcsView' => 'Ics-Ansicht',
		'cal.pi_flexform.icsViewPid' => 'Ics-Ansicht Seite',
		'cal.pi_flexform.icsTemplate' => 'Ics Template',
		'cal.pi_flexform.calUid' => 'Kalender ID',
		'cal.pi_flexform.showIcsLinks' => 'Zeige ics-Link',
		
		'cal.pi_flexform.sheetOtherView' => 'Andere Ansichten',
		'cal.pi_flexform.sidebarTemplate' => 'Sidebar Template',
		'cal.pi_flexform.searchBoxTemplate' => 'Suchbox Template',
		'cal.pi_flexform.showLogin' => 'Zeige Login',
		'cal.pi_flexform.showSearch' => 'Zeige Suche',
		'cal.pi_flexform.showGoto' => 'Zeige Goto',
		'cal.pi_flexform.showCategorySelection' => 'Zeige Kategory Auswahl',
		'cal.pi_flexform.showTomorrowEvents' => 'Zeige morgige Ereignisse',
	),
	'dk' => Array (
		'cal.pi_flexform.sheetGeneral' => 'Generelle indstillinger',
		'cal.pi_flexform.defaultView' => 'Standardvisning',
		'cal.pi_flexform.viewMonth' => 'Vis m&aring;ned',
		'cal.pi_flexform.viewYear' => 'Vis &aring;r',
		'cal.pi_flexform.viewList' => 'Vis liste',
		'cal.pi_flexform.viewWeek' => 'Vis uge',
		'cal.pi_flexform.viewDay' => 'Vis dag',
		'cal.pi_flexform.viewSingle' => 'Vis enkelt',
		'cal.pi_flexform.viewAdmin' => 'Admin',
		'cal.pi_flexform.calendarName' => 'Kalendernavn',
		'cal.pi_flexform.anonymousUserUid' => 'Anonym bruger',
		'cal.pi_flexform.allowSubscribe' =>'Tillad abonnering',
		'cal.pi_flexform.subscribeFeUser' => 'Tillad FE bruger at abonnere',
		'cal.pi_flexform.subscribeWithCaptcha' => 'Tving captcha til at abonnere',
		
		'cal.pi_flexform.sheetYearView' => 'Årsoversigt',
		'cal.pi_flexform.yearViewPid' => 'Årsoversigt side',
		'cal.pi_flexform.yearTemplate' => 'Årsskabelon',
		
		'cal.pi_flexform.sheetMonthView' => 'Månedsoversigt',
		'cal.pi_flexform.monthViewPid' => 'Månedsoversigt side',
		'cal.pi_flexform.monthTemplate' => 'Månedsskabelon',
		'cal.pi_flexform.monthSmallTemplate' => 'Måned lille skabelon',
		'cal.pi_flexform.monthMediumTemplate' => 'Måned medium skabelon',
		'cal.pi_flexform.monthLargeTemplate' => 'Måned stor skabelon',
		'cal.pi_flexform.thisMonthsEvents' => 'Vis denne måneds begivenheder',
		
		'cal.pi_flexform.sheetWeekView' => 'Ugeoversigt',
		'cal.pi_flexform.weekViewPid' => 'Ugeoversigt side',
		'cal.pi_flexform.weekTemplate' => 'Ugeskabelon',
		'cal.pi_flexform.weekStartDay' => 'Ugens startdag',
		
		'cal.pi_flexform.sheetDayView' => 'Dagsoversigt',
		'cal.pi_flexform.dayViewPid' => 'Dagsoversigt side',
		'cal.pi_flexform.dayTemplate' => 'Dagsskabelon',
		'cal.pi_flexform.dayStart' => 'Dag starttid (ttmm)',
		'cal.pi_flexform.dayEnd' => 'Dag sluttid (ttmm)',
		'cal.pi_flexform.gridLength' => 'Trådnetslængde',
		
		'cal.pi_flexform.sheetListView' => 'Listeoversigt',
		'cal.pi_flexform.listViewPid' => 'Listeoversigt side',
		'cal.pi_flexform.listTemplate' => 'Listeskabelon',
		'cal.pi_flexform.starttime' => 'Starttid',
		'cal.pi_flexform.endtime' => 'Sluttid',
		'cal.pi_flexform.maxEvents' => 'Maks. antal begivenheder',
		
		'cal.pi_flexform.sheetEventView' => 'Begivenhedsoversigt',
		'cal.pi_flexform.eventViewPid' => 'Begivenhedsoversigt side',
		'cal.pi_flexform.eventTemplate' => 'Begivenhedsskabelon',
		'cal.pi_flexform.phpicalendarEventTemplate' => 'PhpICalendar begivenhedsskabelon',
		'cal.pi_flexform.createEventTemplate' => 'Opret begivenhedsskabelon',
		'cal.pi_flexform.confirmEventTemplate' => 'Bekræft begivenhedsskabelon',
		'cal.pi_flexform.deleteEventTemplate' => 'Slet begivenhedsskabelon',
		
		'cal.pi_flexform.sheetLocationView' => 'Stedoversigt',
		'cal.pi_flexform.locationViewPid' => 'Stedoversigt side',
		'cal.pi_flexform.locationTemplate' => 'Stedskabelon',
		'cal.pi_flexform.createLocationTemplate' => 'Opret stedskabelon',
		'cal.pi_flexform.confirmLocationTemplate' => 'Bekræft stedskabelon',
		
		'cal.pi_flexform.sheetOrganizerView' => 'Organisatoroversigt',
		'cal.pi_flexform.organizerViewPid' => 'Organisatoroversigt side',
		'cal.pi_flexform.organizerTemplate' => 'Organisatorskabelon',
		
		'cal.pi_flexform.sheetIcsView' => 'Ics-oversigt',
		'cal.pi_flexform.icsViewPid' => 'Ics-oversigt side',
		'cal.pi_flexform.icsTemplate' => 'Ics-skabelon',
		'cal.pi_flexform.calUid' => 'Kalenderid',
		'cal.pi_flexform.showIcsLinks' => 'Vis ics links',
		
		'cal.pi_flexform.sheetOtherView' => 'Anden oversigt',
		'cal.pi_flexform.sidebarTemplate' => 'Sidepanel skabelon',
		'cal.pi_flexform.searchBoxTemplate' => 'Søgeboks skabelon',
		'cal.pi_flexform.showLogin' => 'Vis login',
		'cal.pi_flexform.showSearch' => 'Vis søgeboks',
		'cal.pi_flexform.showGoto' => 'Vis Gå Til',
		'cal.pi_flexform.showCategorySelection' => 'Vis flere',
		'cal.pi_flexform.showTomorrowEvents' => 'Vis morgendagens begivenheder',
	),
	'es' => Array(
       'cal.pi_flexform.sheetGeneral' => 'Ajustes Generales',
       'cal.pi_flexform.defaultView' => 'Vista por omisión',
       'cal.pi_flexform.viewMonth' => 'Vista de mes',
       'cal.pi_flexform.viewYear' => 'Vista de año',
       'cal.pi_flexform.viewList' => 'Vista de lista',
       'cal.pi_flexform.viewWeek' => 'Vista de semana',
       'cal.pi_flexform.viewDay' => 'Vista de día',
       'cal.pi_flexform.viewSingle' => 'Vista simple',
       'cal.pi_flexform.viewAdmin' => 'Admin',
       'cal.pi_flexform.calendarName' => 'Nombre de calendario',
       'cal.pi_flexform.anonymousUserUid' => 'Usuario Anónimo',
       'cal.pi_flexform.allowSubscribe' =>'Permitir suscripción',
       'cal.pi_flexform.subscribeFeUser' => 'Permitir a los usuarios FE suscribirse',
       'cal.pi_flexform.subscribeWithCaptcha' => 'Forzar captcha para suscripción',
       'cal.pi_flexform.sheetYearView' => 'Vista de Año',
       'cal.pi_flexform.yearViewPid' => 'Página de vista de año',
       'cal.pi_flexform.yearTemplate' => 'Plantilla de año',
       'cal.pi_flexform.sheetMonthView' => 'Vista de Mes',
       'cal.pi_flexform.monthViewPid' => 'Página de vista de mes',
       'cal.pi_flexform.monthTemplate' => 'Plantilla de mes',
       'cal.pi_flexform.monthSmallTemplate' => 'Plantilla de mes pequeña',
       'cal.pi_flexform.monthMediumTemplate' => 'Plantilla de mes mediana',
       'cal.pi_flexform.monthLargeTemplate' => 'Plantilla de mes grande',
       'cal.pi_flexform.thisMonthsEvents' => 'Mostrar los eventos de este mes',
       'cal.pi_flexform.sheetWeekView' => 'Vista de Semana',
       'cal.pi_flexform.weekViewPid' => 'Página de vista de semana',
       'cal.pi_flexform.weekTemplate' => 'Plantilla de semana',
       'cal.pi_flexform.weekStartDay' => 'Día de inicio de la semana',
       'cal.pi_flexform.sheetDayView' => 'Vista de Día',
       'cal.pi_flexform.dayViewPid' => 'Página de vista de día',
       'cal.pi_flexform.dayTemplate' => 'Plantilla de día',
       'cal.pi_flexform.dayStart' => 'Hora de inicio del día (hhmm)',
       'cal.pi_flexform.dayEnd' => 'Hora de fin del día (hhmm)',
       'cal.pi_flexform.gridLength' => 'Largo de la rejilla',
       'cal.pi_flexform.sheetListView' => 'Vista de Lista',
       'cal.pi_flexform.listViewPid' => 'Página de vista de lista',
       'cal.pi_flexform.listTemplate' => 'Plantilla de lista',
       'cal.pi_flexform.starttime' => 'Hora de inicio',
       'cal.pi_flexform.endtime' => 'Hora de finalización',
       'cal.pi_flexform.maxEvents' => 'Máximo de eventos',
       'cal.pi_flexform.sheetEventView' => 'Vista de Evento',
       'cal.pi_flexform.eventViewPid' => 'Página de Vista de Evento',
       'cal.pi_flexform.eventTemplate' => 'Plantilla de evento',
       'cal.pi_flexform.phpicalendarEventTemplate' => 'Plantilla de evento PhpICalendar',
       'cal.pi_flexform.createEventTemplate' => 'Crear plantilla de evento',
       'cal.pi_flexform.confirmEventTemplate' => 'Plantilla de confirmar evento',
       'cal.pi_flexform.deleteEventTemplate' => 'Plantilla de borrar evento',
       'cal.pi_flexform.sheetLocationView' => 'Vista de Localidad',
       'cal.pi_flexform.locationViewPid' => 'Página de vista de localidad',
       'cal.pi_flexform.locationTemplate' => 'Plantilla de localidad',
       'cal.pi_flexform.createLocationTemplate' => 'Plantilla de crear localidad',
       'cal.pi_flexform.confirmLocationTemplate' => 'Plantilla de confirmar localidad',
       'cal.pi_flexform.sheetOrganizerView' => 'Vista de Organizador',
       'cal.pi_flexform.organizerViewPid' => 'Página de vista de organizador',
       'cal.pi_flexform.organizerTemplate' => 'Plantilla de organizador',
       'cal.pi_flexform.sheetIcsView' => 'Vista ICS',
       'cal.pi_flexform.icsViewPid' => 'Página de vista ICS',
       'cal.pi_flexform.icsTemplate' => 'Plantilla ICS',
       'cal.pi_flexform.calUid' => 'Identificador de Calendario',
       'cal.pi_flexform.showIcsLinks' => 'Mostrar enlaces ICS',
       'cal.pi_flexform.sheetOtherView' => 'Otra Vista',
       'cal.pi_flexform.sidebarTemplate' => 'Plantilla de barra lateral',
       'cal.pi_flexform.searchBoxTemplate' => 'Plantilla de búsqueda',
       'cal.pi_flexform.showLogin' => 'Mostrar acceso',
       'cal.pi_flexform.showSearch' => 'Mostrar búsqueda',
       'cal.pi_flexform.showGoto' => 'Mostrar ir hacia',
       'cal.pi_flexform.showCategorySelection' => 'Mostrar múltiples',
       'cal.pi_flexform.showTomorrowEvents' => 'Mostrar los eventos del día siguiente',
   ) 
);
?>
