<?php
$timezones = Array (
					Array('(GMT-11:00) Apia', 'GMT-11:00'),
					Array('(GMT-11:00) Midway', 'SST'),
					Array('(GMT-11:00) Niue', 'NUT'),
					Array('(GMT-10:00) Fakaofo', 'TKT'),
					Array('(GMT-10:00) Hawaii', 'HST'),
					Array('(GMT-10:00) Rarotonga', 'CKT'),
					Array('(GMT-10:00) Tahiti', 'TAHT'),
					Array('(GMT-09:30) Marquesas', 'MART'),
					Array('(GMT-09:00) Alaska Standard Time', 'AKST'),
					Array('(GMT-09:00) Gambier', 'GAMT'),
					Array('(GMT-08:00) Pacific Time', 'PST'),
					Array('(GMT-07:00) Mountain Time', 'MST'),
					Array('(GMT-06:00) Central Standard Time', 'CST'),
					Array('(GMT-05:00) Eastern Standard Time', 'EST'),
					Array('(GMT-05:00) Colombia Time', 'COT'),
					Array('(GMT-04:00) Atlantic Standard Time', 'AST'),
					Array('(GMT-04:00) Asuncion', 'PYT'),
					Array('(GMT-04:00) Boa Vista', 'AMT'),
					Array('(GMT-04:00) Caracas', 'VET'),
					Array('(GMT-04:00) La Paz', 'BOT'),
					Array('(GMT-04:00) Santiago', 'CLT'),
					Array('(GMT-04:00) Stanley', 'FKT'),
					Array('(GMT-03:30) Newfoundland Standard Time', 'NST'),
					Array('(GMT-03:00) Araguaina', 'BRT'),
					Array('(GMT-03:00) Buenos Aires', 'ART'),
					Array('(GMT-03:00) Cayenne', 'GFT'),
					Array('(GMT-03:00) Western Greenland Time', 'WGT'),
					Array('(GMT-03:00) Miquelon', 'PMST'),
					Array('(GMT-03:00) Montevideo', 'UYT'),
					Array('(GMT-03:00) Paramaribo', 'SRT'),
					Array('(GMT-02:00) Noronha', 'FNT'),
					Array('(GMT-02:00) South Georgia', 'GST'),
					Array('(GMT-02:00) Noronha', 'FNT'),
					Array('(GMT-01:00) Scoresbysund', 'EGT'),
					Array('(GMT-01:00) Azores', 'AZOT'),
					Array('(GMT-01:00) Cape Verde', 'CVT'),
					Array('(GMT+00:00) Greenwich Mean Time', 'GMT'),
					Array('(GMT+00:00) Western European Time', 'WET'),
					Array('(GMT+00:00) Coordinated Universal Time', 'UTC'),
					Array('(GMT+01:00) Western African Time', 'WAT'),
					Array('(GMT+01:00) Central European Time', 'CET'),
					Array('(GMT+01:00) Eastern Greenland Time', 'EGT'),
					Array('(GMT+01:00) Middle Europe Time', 'MET'),
					Array('(GMT+02:00) Eastern European Time', 'EET'),
					Array('(GMT+02:00) Central African Time', 'CAT'),
					Array('(GMT+02:00) South Africa Standard Time', 'SAST'),
					Array('(GMT+02:00) Israel Standard Time', 'IST'),
					Array('(GMT+03:00) Eastern African Time', 'EAT'),
					Array('(GMT+03:00) Syowa', 'SYOT'),
					Array('(GMT+03:00) Arabia Standard Time', 'AST'),
					Array('(GMT+03:00) Moscow Standard Time', 'MSK'),
					Array('(GMT+03:00) Iran', 'IRT'),
					Array('(GMT+04:00) Aqtau', 'AQTT'),
					Array('(GMT+04:00) Azerbaijan', 'AZT'),
					Array('(GMT+04:00) Gulf Standard Time', 'GST'),
					Array('(GMT+04:00) Georgia', 'GET'),
					Array('(GMT+04:00) Armenia', 'AMT'),
					Array('(GMT+04:00) Samara', 'SAMT'),
					Array('(GMT+04:00) Seychelles', 'SCT'),
					Array('(GMT+04:00) Mauritius', 'MUT'),
					Array('(GMT+04:00) Reunion', 'RET'),
					Array('(GMT+04:30) Afghanistan', 'AFT'),
					Array('(GMT+05:00) Aqtobe', 'AQTT'),
					Array('(GMT+05:00) Turkmenistan', 'TMT'),
					Array('(GMT+05:00) Kirgizstan', 'KGT'),
					Array('(GMT+05:00) Tajikistan', 'TJT'),
					Array('(GMT+05:00) Pakistan', 'PKT'),
					Array('(GMT+05:00) Uzbekistan', 'UZT'),
					Array('(GMT+05:00) Yekaterinburg', 'YEKT'),
					Array('(GMT+05:00) French Southern & Antarctic Lands', 'TFT'),
					Array('(GMT+05:00) Maldives', 'MVT'),
					Array('(GMT+05:30) India Standard Time', 'IST'),
					Array('(GMT+05:45) Nepal', 'NPT'),
					Array('(GMT+06:00) Mawson', 'MAWT'),
					Array('(GMT+06:00) Vostok time', 'VOST'),
					Array('(GMT+06:00) Alma-Ata', 'ALMT'),
					Array('(GMT+06:00) Sri Lanka', 'LKT'),
					Array('(GMT+06:00) Bangladesh', 'BDT'),
					Array('(GMT+06:00) Novosibirsk', 'NOVT'),
					Array('(GMT+06:00) Omsk', 'OMST'),
					Array('(GMT+06:00) Bhutan', 'BTT'),
					Array('(GMT+06:00) Indian Ocean Territory', 'IOT'),
					Array('(GMT+06:30) Myanmar', 'MMT'),
					Array('(GMT+06:30) Cocos Islands', 'CCT'),
					Array('(GMT+07:00) Davis', 'DAVT'),
					Array('(GMT+07:00) Indochina', 'ICT'),
					Array('(GMT+07:00) Hovd', 'HOVT'),
					Array('(GMT+07:00) West Indonesia Time', 'WIT'),
					Array('(GMT+07:00) Krasnoyarsk', 'KRAT'),
					Array('(GMT+07:00) Christmas Island', 'CXT'),
					Array('(GMT+08:00) Western Standard Time (Australia)', 'WST'),
					Array('(GMT+08:00) Brunei', 'BNT'),
					Array('(GMT+08:00) China Standard Time', 'CST'),
					Array('(GMT+08:00) Hong Kong', 'HKT'),
					Array('(GMT+08:00) Irkutsk', 'IRKT'),
					Array('(GMT+08:00) Malaysia', 'MYT'),
					Array('(GMT+08:00) Philippines', 'PHT'),
					Array('(GMT+08:00) Singapore', 'SGT'),
					Array('(GMT+09:00) Choibalsan', 'CHOT'),
					Array('(GMT+09:00) East Timor Time', 'TPT'),
					Array('(GMT+09:00) East Indonesia Time', 'EIT'),
					Array('(GMT+09:00) Korea Standard Time', 'KST'),
					Array('(GMT+09:00) Japan Standard Time', 'JST'),
					Array('(GMT+09:00) Yakutsk', 'YAKT'),
					Array('(GMT+09:00) Palau', 'PWT'),
					Array('(GMT+09:00) Central Standard Time', 'CST'),
					Array('(GMT+10:00) Eastern Standard Time', 'EST'),
					Array('(GMT+10:00) Dumont-d\'Urville', 'DDUT'),
					Array('(GMT+10:00) Sakhalin', 'SAKT'),
					Array('(GMT+10:00) Vladivostok', 'VLAT'),
					Array('(GMT+10:00) Chamorro Standard Time', 'ChST'),
					Array('(GMT+10:00) Papua New Guinea', 'PGT'),
					Array('(GMT+10:00) Truk', 'TRUT'),
					Array('(GMT+10:00) Yap', 'YAPT'),
					Array('(GMT+10:30) Load Howe Standard Time', 'LHST'),
					Array('(GMT+11:00) Magadan', 'MAGT'),
					Array('(GMT+11:00) Vanuatu', 'VUT'),
					Array('(GMT+11:00) Solomon Is.', 'SBT'),
					Array('(GMT+11:00) Kosrae', 'KOST'),
					Array('(GMT+11:00) New Caledonia', 'NCT'),
					Array('(GMT+11:00) Ponape', 'PONT'),
					Array('(GMT+11:30) Norfolk', 'NFT'),
					Array('(GMT+12:00) New Zealand Standard Time', 'NZST'),
					Array('(GMT+12:00) Anadyr', 'ANAT'),
					Array('(GMT+12:00) Petropavlovsk-Kamchatski', 'PETT'),
					Array('(GMT+12:00) Marshall Islands', 'MHT'),
					Array('(GMT+12:00) Fiji', 'FJT'),
					Array('(GMT+12:00) Tuvalu', 'TVT'),
					Array('(GMT+12:00) Marshall Islands', 'MHT'),
					Array('(GMT+12:00) Nauru', 'NRT'),
					Array('(GMT+12:00) Gilbert Is.', 'GILT'),
					Array('(GMT+12:00) Wake', 'WAKT'),
					Array('(GMT+12:00) Wallis & Futuna', 'WFT'),
					Array('(GMT+12:45) Chatham Standard Time', 'CHAST'),
					Array('(GMT+13:00) Phoenix Is.', 'PHOT'),
					Array('(GMT+13:00) Tonga', 'TOT'),
					Array('(GMT+14:00) Line Is.', 'LINT'));
?>